set -g default-terminal "screen-256color"
set -as terminal-features ',xterm-kitty:RGB'

# set -g set-clipboard on # TODO: WHY??? it works???
set -g mouse on # allows me to click on tabs etc.
set -g status-interval 3 # Update status bar every 3 seconds.
set -g detach-on-destroy off

set -g allow-passthrough on # allows custom codes to go thru tmux.
# To allow windows to be focusable see the icon we use this so that its not a background process.
set-option -g default-command "reattach-to-user-namespace -l zsh"

# set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# CMD-Shift vim keys to switch windows -> see kitty.conf

# 1 indexing for windows.
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Catppuccin options
set -g @catppuccin_flavour 'mocha'
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
# Window names
set -g status-left-length 100
set -g status-left "#[fg=${green_soft},bold]  Session #S #[fg=${gray_light},nobold] | "

# Plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator' # Navigate between tmux & nvim panes.
set -g @plugin 'catppuccin/tmux' # Theme slay
set -g @plugin 'tmux-plugins/tmux-yank' # prefix+[ shift/ctrl+v
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart.
set -g @plugin 'tmux-plugins/tmux-continuum' # saves sessions after 15 minutes.
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'


# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane # Don't unselect after mouse drag.

# New panes remaps & keep directory
bind '-' split-window -v -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
bind -r m resize-pane -Z 5 # maximizes


# Always run at very end.
run '~/.config/tmux/plugins/tpm/tpm' # plugin manager

# In order to install new extensions after sourcing tmux.conf, run uncomment this
# run '~/.config/tmux/plugins/tpm/bin/install_plugins'
